# archive creates and publishes an apk for testing
name: archive
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: checkout
        uses: actions/checkout@v2
      - run: ./gradlew clean assembleDevFullRelease
      - name: uploads dev apk
        uses: actions/upload-artifact@v3
        with:
          name: dev-apk
          path: app/build/outputs/apk/devFull/release